<a href="https://colab.research.google.com/github/VKline333/Statistics/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples =np.random.normal(100,15,1000)
samples

array([111.73823085,  96.68275764,  73.47027597, 103.86179816,
        90.92701647, 117.88391123, 105.11889891,  81.1734473 ,
       138.22769011, 142.77281337,  96.64523151, 101.34700702,
        91.00389659,  92.16516019,  84.3156917 , 132.73051555,
        93.77251704, 119.43321282,  67.86936798, 102.53959904,
        94.12202655, 103.42401727, 123.26195283,  94.81634168,
       129.10829237, 106.56436562, 103.65510256, 104.86069308,
       110.89037529, 114.30066534,  99.55794143,  88.05617052,
        90.37659251, 101.91289546, 108.34209916, 104.38981026,
       107.51585255,  96.53320412, 100.24466403,  82.5635611 ,
        89.43839295, 116.53359836, 113.28105419, 132.61827408,
        73.98698161, 101.97964783,  89.08783335,  60.08065815,
       118.54837109, 104.98199981, 104.45241359, 103.35321445,
       102.81814361, 102.97792707, 113.32568222,  79.57297427,
       108.1410486 , 112.85869236, 102.01852422,  60.87835483,
        97.60290056, 100.66104242,  87.90964009,  94.01758838,
        78.33692161,  91.83858124, 120.22370711, 124.75841586,
       104.30977626, 107.72733792, 106.72842998,  82.82615244,
       134.38378549,  98.58893814,  72.07553839,  78.46035205,
        98.81182026,  97.78560824, 121.12564065,  91.99233347,
       116.34442219, 101.37996774,  85.32838213, 117.80885528,
       103.52682341,  76.60863583,  75.62392415, 112.63900226,
       113.39147972, 114.04942067,  82.9031806 , 108.26548787,
        94.51931317,  99.52914534,  79.14963148, 124.27272977,
       105.62043669, 115.44399263,  74.41570754, 101.96347319,
       105.85147071,  88.96917643, 120.70281226,  97.01709888,
       143.94433884, 124.00806037,  94.42469189,  96.51271379,
       108.12562279, 116.06794754,  71.1194051 ,  98.58668335,
       121.13673846,  84.28175817, 100.00472285,  76.17931705,
       120.02542709, 106.45596495, 107.04116291,  74.75968944,
        90.41319257, 105.60617973, 110.8920466 , 115.71323438,
        95.62268636,  62.0580337 ,  85.07450902, 119.84421573,
       118.51956164,  99.47622648, 124.96646024, 109.10494057,
       114.19728585, 108.9024924 , 105.01790349,  93.99761307,
        81.20997176,  94.14228867, 126.27593461, 109.54685516,
       120.21029544, 108.19206651, 113.10442435, 108.06767463,
        95.80842671,  89.12936773, 102.78146311, 119.50548467,
       113.49624285, 108.08379261,  95.57662203,  83.3941659 ,
        98.33740789, 121.51932298, 134.2482109 , 103.911115  ,
       110.77603983, 128.93298415,  93.77264756,  93.18366804,
       113.92812905,  85.39956803,  76.6950524 ,  96.87124301,
        90.65646204, 132.45232245, 107.78494282, 114.84917877,
       110.63027818, 108.3455398 ,  95.26666712,  87.29261245,
        92.66886349, 113.6429463 , 124.68647547,  99.29097456,
       111.37313751, 116.9290256 , 114.90456242, 126.11904804,
       103.9286247 ,  90.31634626, 122.14077105,  93.38599704,
        96.6753607 , 103.59779099,  95.87877083,  66.32559455,
       104.7083693 ,  80.40068303, 136.8888238 ,  93.69538552,
       124.90784717, 145.93439477, 101.9932224 , 108.30394593,
       104.50932466, 100.56792276,  88.13744694,  88.26604675,
        99.42880984, 122.82146507, 111.25279432,  94.54362622,
       105.17233255,  76.19579146, 113.2043717 , 108.30397947,
        86.9540729 ,  80.92457924,  96.75762682,  69.36365417,
       130.27753668, 111.21351506,  85.23833287,  98.79995397,
       107.14621481, 112.4322681 ,  78.20750403, 116.44516647,
       113.13017627,  92.45676654, 120.08907896, 115.27571123,
        78.43717784,  82.46481329, 111.85756527,  95.35038982,
       114.09274565, 124.34093583,  80.55109994,  86.31138261,
       104.77769437,  99.54177999,  98.85300695,  68.80290663,
        81.2160213 , 122.51356022, 117.79352147, 109.82691969,
        92.34016485, 123.16061318, 103.32899276,  78.6571943 ,
       107.90081432, 111.16499009, 102.98956718,  88.77063353,
       111.74746355,  87.15082551,  88.04239461,  98.26361696,
       104.83110662, 102.20457363,  81.57054001, 102.33400337,
       114.45397272,  92.82347256, 101.05050893, 103.78901678,
       107.37652285, 120.3137045 ,  68.66404316,  78.41235493,
       104.98937342, 140.18177218, 103.80119916,  79.06109676,
       109.2107501 ,  83.06229786,  96.83775031, 106.03520228,
       121.81431925,  86.98520949,  79.22741612,  99.82639515,
       116.35914096,  86.05684818, 107.65461358,  94.68067981,
        91.23748645, 105.0848347 , 106.83499174, 112.84568803,
        87.91885645, 114.83491342, 109.34854951,  97.34472724,
        87.13800277, 114.99394858, 100.27212642,  90.12678074,
        93.64384671,  93.06595599,  90.69429752, 103.16594009,
        99.92772213, 109.96315644, 110.71616371, 102.87604681,
        97.67023705, 105.0842487 ,  77.19583189, 114.87812162,
       129.20172995, 120.13872946,  87.16895947, 104.45569437,
        90.89739914,  89.46477037,  85.29758025,  98.95163467,
       105.95648083, 120.0525884 ,  57.27171951, 110.47948197,
        98.61582235, 116.48396587, 105.57427934,  83.15157951,
        96.90225079,  78.36885617,  90.24306754,  76.60854818,
        89.14723072,  88.08424532, 116.47471131,  97.24558127,
       111.37382067,  94.40066185,  92.29297858,  71.43404731,
       121.98404685,  98.64242787,  97.02593484, 106.74039489,
       127.07998907, 116.50944499, 126.01654549,  97.41911298,
       125.65434389,  73.96006764,  92.68396915, 121.31116615,
       103.77737869, 106.24720954, 108.15496301,  95.23078524,
        83.58342487, 117.62951876,  87.72492552, 123.16495542,
        72.29872826, 109.28316451, 106.25197729,  72.79329306,
       113.53097625,  86.56193606,  89.91327191, 103.15876751,
       107.96917305,  79.10902703,  77.67310669, 109.40565039,
       101.79016794, 128.85174878, 103.62150824,  95.86734939,
        87.90578094,  78.34501599, 118.99399236, 105.48195727,
        84.59402894, 108.65419457,  82.13972584,  96.23870261,
       117.7361193 , 102.44819172, 116.14019502,  94.26759056,
       108.63880293, 111.09622364,  90.45711321,  97.16839239,
        85.82780025, 111.83841993, 103.68713346, 122.01348521,
        79.92967416,  70.9160861 ,  95.17607075,  97.02064147,
       108.9331389 , 100.62585094,  98.55193113, 101.75582701,
       116.56467001,  91.22924202, 112.78871048, 118.15508597,
       102.70993073, 103.0035932 , 110.08749468,  87.76131509,
       103.42131857,  80.15496943,  88.65029398, 106.6227326 ,
        88.39260126, 106.21026905, 108.05597519,  88.47854891,
        86.04944   ,  77.74997646,  89.62084952,  98.75424383,
       107.84149128, 118.29678201,  93.59426623, 107.15097641,
       101.57397237,  90.00237662,  97.49299135, 124.91250033,
        96.33176674, 123.58502951, 102.37587288,  96.60316492,
       128.17414695,  91.17538558,  95.93068913, 111.98233902,
       111.87392956, 105.98071053, 115.81208013,  86.2164649 ,
        67.1871477 , 125.77329347, 113.67349354,  71.06583147,
        98.22278577,  75.2014962 ,  93.34181374, 114.39798055,
        94.68287498, 101.23822337,  88.5053727 , 103.10357419,
        95.90207091,  97.62068379,  91.31044338, 120.85518965,
       119.23100386, 113.6379084 , 122.16126975, 102.25601358,
       107.13352137, 104.85767242,  91.73765089,  70.83480448,
        91.12215605,  87.32581327, 121.92023578,  99.6379252 ,
        97.09823205, 128.81714014, 109.36420794, 118.35696952,
        92.60354993,  97.81462807, 110.36791315,  92.21576449,
        92.40633797,  95.23125061, 125.91039365,  99.19794883,
        74.37340607, 113.06020352,  76.57188071,  82.82685977,
       118.62904447,  98.16721282,  54.36915257,  97.71693041,
        91.03882832,  86.69920144, 114.44363642,  94.77645153,
        93.22491367, 109.91391467, 100.5134055 , 111.05213893,
       101.40779033,  87.06245542,  90.67009155,  78.90273825,
        98.07180705, 114.44093446, 107.98526762, 137.64879982,
        92.8094078 ,  76.50289507,  82.15863745,  73.51064927,
        69.14176892,  95.59900825,  97.9055257 , 114.07413575,
       102.42104909,  83.11968918,  98.16187062,  61.32902617,
       100.18034711, 119.10780975,  85.31376417, 101.77562511,
       123.83547435,  87.82976426, 101.36929565,  86.02393553,
       110.55598312, 108.49528526, 110.54312993, 105.74860164,
       110.68285895,  96.2803993 ,  85.74635871, 126.07734399,
        93.95123948, 104.74646327, 104.94111335,  65.6909863 ,
       106.43195468, 106.5974925 , 102.59795486, 108.19997548,
        95.38365689, 107.00912867, 117.19048042,  85.52815432,
        95.84260097, 100.7493744 , 118.97158499, 116.61919683,
       102.30706392,  82.54827188, 105.43573208, 103.97933008,
        95.36905607,  90.24826823,  97.59569535,  89.1665742 ,
       108.07045427,  97.19663698,  84.90914463,  91.08074394,
       143.99537258,  94.77506418, 103.37879816, 121.23650296,
        88.72179844,  82.73513123, 104.69819204, 111.53969504,
       116.33486942, 101.35372134, 103.29741389,  90.17575336,
        70.46720489,  71.58909176, 126.58794466, 125.10182452,
       107.06491493,  99.81608893,  91.52101273,  90.54074562,
        98.80994129, 101.57329424, 105.68664101,  99.8551462 ,
       115.29023948, 102.4688736 , 105.30585847, 101.44925865,
       100.14097852, 104.46176557, 113.31201856, 109.01849077,
        95.21273843, 113.12259673,  93.93305884,  90.40965473,
       119.26798945, 108.49835728,  94.67105201, 109.70118573,
       106.51062007, 110.75513762,  93.47033073, 121.25621457,
       124.21203497, 112.62516526, 136.92746606,  96.93727743,
        83.25869341, 120.9597678 , 106.57501893,  87.16882451,
        96.10503579,  90.94171486, 136.72371566, 125.63242528,
       100.4535945 , 113.90260247, 121.93743056, 118.39054555,
        85.22195396,  90.81123216,  83.91248613, 112.23510646,
        76.44633512, 105.94275771, 108.01668909, 106.19406042,
        97.73373584,  97.07146005,  87.7325343 ,  89.07392591,
       107.40696851,  84.2249971 , 101.63198575,  85.74201629,
        77.67891315, 101.23542324,  84.77572614,  99.71030148,
        97.85920418,  91.99422429, 119.72890813, 112.26760927,
        93.50272498,  84.04103888,  85.77064167, 113.68610509,
       106.3868335 ,  84.65249505, 112.48059245,  83.79074576,
        97.22594226, 108.74024483, 116.97119946, 113.16885894,
       110.62343827,  95.36625924,  85.46129803,  92.54688419,
       102.91848021,  96.08727126,  89.08691716,  64.79573214,
       115.39869823,  85.58675603,  95.34641881,  88.77570712,
       104.7371835 , 108.30814849,  61.21249708,  96.08795327,
       100.6990825 , 117.36127392, 107.47603303,  93.60024263,
       106.42122066,  95.50848511, 100.17507706, 118.15799898,
        97.6808902 , 115.68987602,  93.4498031 , 112.33487194,
       108.44991507,  76.17653963, 101.77535359, 103.28111922,
       120.71222986, 109.29826253,  99.85750844, 111.19484616,
       127.27834717, 113.24981828, 116.20476107,  92.76159647,
        95.61139937,  87.68139449,  92.24082086, 110.44564009,
       103.63041566, 107.84706533,  84.68069639,  82.00661466,
        73.2859149 ,  81.76922643, 108.53890522, 121.94452024,
       136.15003796, 112.09894063,  95.10837729,  92.74764401,
       118.84668083, 114.70124343, 113.99426555,  98.50968007,
       125.73575715,  98.334486  ,  96.83757562, 109.35320394,
       117.51106748,  89.62881201,  82.54074228,  99.47237352,
       101.97886849, 118.30544888,  74.41654263, 118.99847473,
       105.09795385, 107.74087339,  69.29824802,  86.32837791,
       116.97823973,  82.22597532, 111.29634693,  77.89491231,
        82.92455112, 109.13374528, 116.57040447,  96.96078522,
        98.05881612, 110.27442303, 107.75128033, 103.46149934,
       105.25082897, 104.49490211, 107.50357089, 129.14060971,
       104.29588715,  86.38612076, 112.00741482,  61.37008266,
        95.66775679,  71.21310554,  86.59468694, 111.04613756,
        77.29445276,  96.02411806,  93.33273466, 125.09991241,
       140.52234036,  99.97032281, 112.69520316,  66.78343637,
       115.74828742, 132.32284922, 106.16218952, 115.75286807,
        91.24584181, 105.72604691,  92.85565693,  83.92461059,
       116.56884327, 101.2685433 ,  89.63284472, 106.36178922,
       102.51531933, 117.58132707,  75.24170314,  92.8812967 ,
        78.53936231, 112.15708818, 128.28431469,  67.67400032,
       102.67242496, 109.42586435, 102.19954538,  96.53114692,
       101.66499944, 124.92758836,  82.3248028 , 114.34603476,
       102.0063213 , 139.40459977,  72.94544396,  99.59529579,
        91.3474232 ,  96.20022009, 105.49172872,  94.73221196,
       105.44909731, 101.11032023, 120.74120045,  74.14707057,
       116.14348818,  95.02831342, 100.62714059,  82.51207374,
        94.55974731, 105.04225697, 100.31501162,  97.81973704,
        96.50434343, 107.79490087,  84.89154995,  95.53393077,
        75.86299447, 112.40729262, 103.39272752,  65.83573653,
       104.87807873, 103.73484939, 106.88097833,  96.95254001,
        92.67656739,  70.29035395, 119.27851915,  88.9259181 ,
       124.53791213,  84.17238881, 114.57401265, 111.94180832,
        92.85368421, 113.76651873,  83.47136371,  74.63786349,
        83.93493617,  95.45841497, 133.8316555 ,  95.88884533,
       103.50793436, 105.37768462, 105.32845215, 109.82526253,
        99.26297203,  93.82484042, 103.16953189,  90.19329927,
       115.31363215,  96.23150158,  84.31176299, 103.49990432,
       104.11892389, 107.83927138, 110.53699465,  87.38458169,
       103.597254  ,  72.73648934,  81.33884167,  98.36402932,
        92.22230317, 102.80807406,  96.61882145,  97.60545006,
        84.73290159, 110.02024756, 104.06301288, 104.2672018 ,
        85.42939323,  92.33941702, 110.59418085,  93.75186286,
        98.71714003,  91.7616043 ,  81.10007528,  84.15423738,
        94.12330801,  79.19078567,  85.41610237, 112.14758359,
       107.32696503, 106.79690135, 105.29800112, 113.42474356,
       106.28896075,  75.96623642,  62.36447005, 105.47315611,
        82.03397378, 112.09308532, 117.19554519,  94.41029175,
       103.99219334,  91.48384232,  75.83526307, 101.83556781,
        99.83516914,  98.969981  ,  84.22397406, 135.28085023,
       112.47388413,  90.53613668,  85.61560459,  89.27287638,
       114.98417426,  93.51118143,  90.37688829,  86.36246696,
       106.27402916, 107.80175527,  93.80808438,  99.09430438,
        90.5665616 , 122.28346399,  97.39529838,  95.28523284,
        84.67362531,  88.6269551 ,  68.74128497,  66.34773152,
       119.83939096,  91.38974456,  98.37125216, 102.02094663,
        89.26858287,  83.6165951 , 125.73371088,  93.39513288,
       106.18011511, 104.0582673 , 109.3060679 ,  76.87756277,
       109.74912178,  96.45483842, 120.98498215, 126.3241762 ,
       108.73882145, 115.77619475, 107.38039462, 114.78439982,
       100.46170424, 118.58842185,  94.49914722,  89.06020892,
        94.08027903,  94.89522874, 103.46717477, 108.45831094,
       121.52192118,  99.44037054,  92.91058474,  95.41330105,
       100.41968656,  82.4376251 ,  94.65351587,  97.0061935 ,
        81.18581001,  89.41309323, 100.63453246,  94.24287664,
       104.18966747,  94.13693387, 106.49769761,  94.18047702,
        83.37658996,  69.20033058,  84.19621482, 116.06005872,
        78.134161  , 100.91684101, 116.83366854,  84.96992195,
        89.22162945, 116.75513227, 113.30244824,  94.66732277,
       105.37399105, 101.79431982,  84.37055186,  92.43739268,
       114.58234226,  92.16170327, 100.59110829, 111.25630352,
       100.00814665,  79.12316859, 102.61795923,  95.70705651,
        78.28666443, 100.55115573,  91.0478536 , 105.78826198,
       110.96045945,  91.10446478, 121.39988866, 107.46994974,
       112.53913526,  96.82895544, 111.76626674,  96.38542315,
        93.7405389 ,  58.83143293, 116.20676212,  98.43012191])

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)

In [ ]:
mean

100.4708492569046

In [ ]:
median

100.72422844991448

In [ ]:
mode

ModeResult(mode=array([54.36915257]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples,25)
q3 = np.percentile(samples,75)
iqr = q3 - q1

In [ ]:
min

54.36915256618231

In [ ]:
max

145.93439477496398

In [ ]:
q1

90.78199850322225

In [ ]:
q3

110.64342337105236

In [ ]:
iqr

19.86142486783011

Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
std_dev = np.std(samples)

In [ ]:
variance

227.045642627979

In [ ]:
std_dev

15.068033800996698

Compute the **skewness** and **kurtosis**

In [ ]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)

In [ ]:
skewness

-0.06476531991402644

In [ ]:
kurtosis

0.03795101034289994

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [3]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [6]:
y = np.random.randint(100, size=10)
y

array([47, 50, 48,  1, 18, 84, 22, 50, 54, 20])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [7]:
r = np.corrcoef(x,y)
r

array([[ 1.        , -0.05818279],
       [-0.05818279,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
np.corrcoef(tips["total_bill"],tips["tip"])

array([[1.        , 0.67573411],
       [0.67573411, 1.        ]])